os: osx
script:
  # - ./travis.sh
env:
  global:
  - secure: JcILjYgQi42xGNuCITe9jre8P93sNu+bctJrb3ciVubRxbUqk3bTHhUlzvDY4QetEblN/uA0fd2DKSPlMO+Z4DcQ17C+XXN3H5MH/2YaMfkdyDcjg0vms7DJruTqgpm4jqNhFYnDR2PAEENtgdNIVulvh5Ih/fcm/60L32PwyrlYppPTkMh6j5rV1bkqkqc06xQusuLfcVN+jx16CNYn/szZPIhTt2+mB08Tv2qJYO4OMQeyRqH8QoOMIHu3rVHwE4rFXLakhoakL3kLYHJ8BlqPxDHr1fElFEv+RQEt48fBBjf5nrkQPdFrclWG2Pd5/aNEvvaIuAilaZMBsh93gL50QQwq3sV4CESh1TSph37/pIhogPfS9NsoedxAan8GTTSYyZGvv5Xr4pxrxsY4sgEsvgESdw2dgWoZBxxWCuoapmwdHwA2WfLThnuPnYFGX8DZ4FmE6a/OVWJt3cb8Shpdrc3gnElCEBt/hSrcdWzLMSdiLnA24jdbOgmbv9RCe5jib/jC1X/cdb/zq+krtqoqPdOqIeMJAixtHYI7KRRgXz4U/HGDERbDvbkcE3Y8wA/GccgMDARoJ+1SKN2BV0+kPZRo24/iZsiYGJfzs3iXfm6qmUkTlqft/OcZyfzW9fojjwghTecS+tfPIny94JiJSXxpXyrXY2G4PNAT2Ew=
